sudo: required
services:
  - docker

before_install:
  - docker build -t dmaesj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dmaesj/react-test npm test -- --coverage

after_success:
  # build docker images
  - docker build -t dmaesj/multi-client ./client
  - docker build -t dmaesj/multi-server ./server
  - docker build -t dmaesj/multi-worker ./worker
  - docker build -t dmaesj/multi-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker
  - docker push dmaesj/multi-client
  - docker push dmaesj/multi-server
  - docker push dmaesj/multi-worker
  - docker push dmaesj/multi-nginx

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-122627789804"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"